
services:
  replicate-flux-lora:
    image: ghcr.io/rtuszik/replicate-flux-lora:latest
    container_name: replicate-flux-lora
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
    ports:
      - "8080:8080"
    volumes:
      - ${HOST_OUTPUT_DIR}:/app/output
    restart: unless-stopped